spring.application.name=users
server.servlet.context.path=/users
server.port=8081


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/edu_tech_users
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
#logging.level.org.springframework=INFO
#logging.level.root=INFO
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## Email OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=someshkumarrepati@gmail.com
spring.mail.password=wrnbhvqysvvsmwuc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=your-256-bit-minimum-secret-key-change-this-in-production-xxxxx
jwt.expiration-ms=86400000
logging.level.org.springframework.security=DEBUG